### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by Sparklesyo** [nonebot/nonebot-test#15]
运行环境：
- Nonebot2: 2.0.0b2
- Go-CqHttp 反向ws（正向ws也试过）
- python-socketio: 4.6.1
- python-engineio:3.14.2
- nonebot-plugin-test: 0.3.0
- websockets: 10.2

错误信息：
加载时出现：`TypeError: __init__() got multiple values for argument 'sio'`

<img src="https://user-images.githubusercontent.com/54591184/161951318-a7bed86c-e7a1-4bd4-8b62-6c81354c5a7e.png" width = "600" height = "400" align=center />

**Comment by yanyongyu** [comment]
test插件不支持beta版本的nonebot，以后也不再支持
